apiVersion: v1
kind: Service
metadata:
  name: containerwebapp-service
spec:
  type: NodePort
  selector:
    app: containerwebapp
  ports:
    - port: 2000
      targetPort: 2000
      nodePort: 30080
